### ISSUE TITLE
Organism viewer - mutation rate

### ISSUE THREAD

**Issue by kohncory** [DBlackwood/av_ui#24]
I can set the mutation rate with either the slider or typing a value in the field. If using the slider then the field shows a number with a percent sign ("13.475%") within the field, so with the already on the right percent sign, it collectively reads "13.475%%". It doesn't throw the exclamation point "numeric value" error. Running an organism shows that the mutation rate is not being applied. Going back in to enter a number in the field throws the "numeric value" error; deleting the percent sign fixes the problem and mutations are applied.

**Comment by DBlackwood** [comment]
Diane Fixed
