### ISSUE TITLE
Renamed freezer offspring shows old name once dragged back to freezer

### ISSUE THREAD

**Issue by kohncory** [DBlackwood/av_ui#28]
I dragged an organism into the freezer, let it replicate with a mutation rate, then saved the offspring to the freezer and named it X. I right-clicked on the organism in the freezer and changed its name to Y. Later I dragged Y to the freezer and the original name, X, shows in the window/field above the viewing pane showing the replication. It's still correctly named Y in the freezer, but the organism viewer says it's still named X.

**Comment by DBlackwood** [comment]
I think I have this fixed
